### ISSUE TITLE
Clean up prof dev

### ISSUE THREAD

**Issue by iamzoltan** [neuromatch/NeuroAI_Course#162]
Prof dev needs to be cleaned up. This page in particular https://neuroai.neuromatch.io/projects/professional_development/mentorship_program.html needs title cleaning

**Comment by glibesyck** [comment]
@iamzoltan I'm not sure what exactly should be integrated into this page, but I can see through the commit history that it was updated. The only improvement I can suggest is to make a link to the resource clickable; I will do PR on that and mention this issue.

**Comment by glibesyck** [comment]
Closed with #377.
