### ISSUE TITLE
W1D2T1 Doesn't seem to be making use of GPU (CUDA) 

### ISSUE THREAD

**Issue by hallurr** [neuromatch/NeuroAI_Course#376]
The ipynb doesnt seem to send any tensors to the GPU, however it calls does frequently call them to cpu for plotting etc.

**Comment by glibesyck** [comment]
@hallurr thank you for noticing this fact! Removed in #377.

**Comment by glibesyck** [comment]
@all-contributors please add @hallurr for bug
