### ISSUE TITLE
Issue on page /tutorials/W1D2_ComparingTasks/student/W1D2_Tutorial1.html

### ISSUE THREAD

**Issue by ritog** [neuromatch/NeuroAI_Course#380]
A heading is wrong.

In Section 2, of W1D2, https://neuroai.neuromatch.io/tutorials/W1D2_ComparingTasks/student/W1D2_Tutorial1.html#transfer-example-2-autoencoder-to-classification, the heading *should be* **regression to autoencoder**. Not what is written, i.e. "Autoencoder to Classification".

**Comment by glibesyck** [comment]
Hey @ritog! I believe it should be "Autoencoder to Classification" (as we take autoencoder as source model and classification as destination one). Can you please elaborate on your suggestion?

**Comment by ritog** [comment]
Hi, I was confused with the plot name, and may the labels of the plot is what should change. Let me create another PR for that.

**Comment by ritog** [comment]
Sorry, the issue seems to have caused by a plot not loading in time, and leading to confusion. I think the code is okay.
